/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_VentanaPrincipal;

/**
 *
 * @author Marko
 */
public class GUI_Botones extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Botones
     */
   Controlador_FRM_VentanaPrincipal controlador;
    public GUI_Botones() {
        initComponents();
    }
    public void agregarEventos(Controlador_FRM_VentanaPrincipal controlador){
        this.controlador=controlador;
        this.jb_Agregar.addActionListener(controlador);
        this.jb_Buscar.addActionListener(controlador);
        this.jb_Eliminar.addActionListener(controlador);
        this.jb_Modificar.addActionListener(controlador);
    }
public void estadoInicial(){
this.jb_Buscar.setEnabled(true);
this.jb_Agregar.setEnabled(false);
this.jb_Modificar.setEnabled(false);
this.jb_Eliminar.setEnabled(false);

}
public void habilitarAgregar(){
this.jb_Buscar.setEnabled(false);
this.jb_Agregar.setEnabled(true);
this.jb_Modificar.setEnabled(false);
this.jb_Eliminar.setEnabled(false);

}
public void habilitarOpciones(){

this.jb_Buscar.setEnabled(false);
this.jb_Agregar.setEnabled(false);
this.jb_Modificar.setEnabled(true);
this.jb_Eliminar.setEnabled(true
);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_Buscar = new javax.swing.JButton();
        jb_Agregar = new javax.swing.JButton();
        jb_Modificar = new javax.swing.JButton();
        jb_Eliminar = new javax.swing.JButton();

        jb_Buscar.setText("Buscar");

        jb_Agregar.setText("Agregar");

        jb_Modificar.setText("Modificar");

        jb_Eliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_Agregar)
                .addGap(18, 18, 18)
                .addComponent(jb_Modificar)
                .addGap(18, 18, 18)
                .addComponent(jb_Eliminar)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Buscar)
                    .addComponent(jb_Agregar)
                    .addComponent(jb_Modificar)
                    .addComponent(jb_Eliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Agregar;
    private javax.swing.JButton jb_Buscar;
    private javax.swing.JButton jb_Eliminar;
    private javax.swing.JButton jb_Modificar;
    // End of variables declaration//GEN-END:variables
}
