/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Mark
 */
public class GUI_Informacion extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Informacion
     */
    public GUI_Informacion() {
        initComponents();
        cargarDatos();
    }
    
     public String devolverCedula()
    {
        return this.jt_Cedula.getText();
    }
    public void cargarDatos(){
           this.jcb_Horario.removeAllItems();

        for(int i=0;i<10;i++){
    
    this.jcb_Horario.addItem(""+i);
    }

    this.jcb_Horario.setSelectedIndex(4);
    }
    public String[] devolverInformacion(){
    String arreglo[]=new String[4];
        arreglo[0]=this.jt_Cedula.getText();
                arreglo[1]=this.jt_Nombre.getText();
        arreglo[2]=this.jt_Direccion.getText();
        arreglo[3]=""+this.jcb_Horario.getSelectedIndex();

        return arreglo;
    }
public void mostrarInformacion(String arreglo[]){
this.jt_Nombre.setText(arreglo[0]);
this.jt_Direccion.setText(arreglo[1]);
this.jcb_Horario.setSelectedIndex(Integer.parseInt(arreglo[2]));
}
 public void habilitarAgregar()
    {
        this.jt_Cedula.setEnabled(true);

        this.jt_Nombre.setEnabled(true);
        this.jt_Direccion.setEnabled(true);
                this.jcb_Horario.setEnabled(true);

             

    }
public void estadoInicial(){
this.jt_Cedula.setEnabled(true);
this.jt_Direccion.setEnabled(false);
this.jt_Nombre.setEnabled(false);
this.jcb_Horario.setEnabled(false);

}

public void limpiar(){
this.jt_Cedula.setText("");
this.jt_Nombre.setText("");
this.jt_Direccion.setText("");

}
public void deshabilitarCedula(){
   this.jt_Cedula.setEnabled(false);
this.jt_Direccion.setEnabled(true);
this.jt_Nombre.setEnabled(true);
this.jcb_Horario.setEnabled(true);
 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Cedula = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Direccion = new javax.swing.JLabel();
        jl_Horario = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jt_Direccion = new javax.swing.JTextField();
        jcb_Horario = new javax.swing.JComboBox();

        jl_Cedula.setText("Cedula");

        jl_Nombre.setText("Nombre");

        jl_Direccion.setText("Dirección");

        jl_Horario.setText("Horario");

        jcb_Horario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Cedula)
                        .addGap(18, 18, 18)
                        .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Nombre)
                        .addGap(18, 18, 18)
                        .addComponent(jt_Nombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Direccion)
                            .addComponent(jl_Horario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_Direccion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcb_Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_Cedula)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Horario)
                    .addComponent(jcb_Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jcb_Horario;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Direccion;
    private javax.swing.JLabel jl_Horario;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Direccion;
    private javax.swing.JTextField jt_Nombre;
    // End of variables declaration//GEN-END:variables
}
